#01 - Livraria/03 - Livraria MVC DAO/Livraria.Mvc.AppWeb/Models/ErrorViewModel.cs
using System;

namespace Livraria.Mvc.AppWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

#01 - Livraria/03 - Livraria MVC DAO/Livraria.Mvc.AppWeb/Controllers/HomeController.cs
using Livraria.Mvc.AppWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace Livraria.Mvc.AppWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

#01 - Livraria/03 - Livraria MVC DAO/Livraria.Mvc.AppWeb/Controllers/LivroController.cs
using Livraria.Mvc.Domain.Intefaces;
using Livraria.Mvc.Domain.Models.Livros;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace Livraria.Mvc.AppWeb.Controllers
{
    public class LivroController : Controller
    {
        private readonly ILivroDAO _livroDAO;

        public LivroController(ILivroDAO livroDAO)
        {
            _livroDAO = livroDAO;
        }

        // GET: LivroController
        public ActionResult Index()
        {
            List<Livro> livros = _livroDAO.Listar();
            return View(livros);
        }

        // GET: LivroController/Details/5
        public ActionResult Details(int id)
        {
            Livro livro = _livroDAO.ObterPorId(id);
            return View(livro);
        }

        // GET: LivroController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LivroController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(IFormCollection collection)
        {
            try
            {
                Livro livro = new Livro();
                await TryUpdateModelAsync(livro);

                if(collection.Files != null)
                    if (collection.Files[0] != null)
                        if(collection.Files[0].Length > 0)
                        {
                            var filePath = Path.GetTempFileName();

                            using (var stream = System.IO.File.Create(filePath))
                            {
                                await collection.Files[0].CopyToAsync(stream);
                            }

                            var bytes = System.IO.File.ReadAllBytes(filePath);

                            var base64 = Convert.ToBase64String(bytes);

                            livro.Imagem = base64;
                        }                        

                livro = _livroDAO.Inserir(livro);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LivroController/Edit/5
        public ActionResult Edit(int id)
        {
            Livro livro = _livroDAO.ObterPorId(id);
            return View(livro);
        }

        // POST: LivroController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, IFormCollection collection)
        {
            try
            {
                Livro livro = new Livro();
                await TryUpdateModelAsync(livro);

                if (collection.Files != null)
                    if (collection.Files[0] != null)
                        if (collection.Files[0].Length > 0)
                        {
                            var filePath = Path.GetTempFileName();

                            using (var stream = System.IO.File.Create(filePath))
                            {
                                await collection.Files[0].CopyToAsync(stream);
                            }

                            var bytes = System.IO.File.ReadAllBytes(filePath);

                            var base64 = Convert.ToBase64String(bytes);

                            livro.Imagem = base64;
                        }

                _livroDAO.Alterar(livro);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LivroController/Delete/5
        public ActionResult Delete(int id)
        {
            Livro livro = _livroDAO.ObterPorId(id);
            return View(livro);
        }

        // POST: LivroController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                Livro livro = new Livro();
                await TryUpdateModelAsync(livro);

                _livroDAO.Deletar(livro);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

#01 - Livraria/03 - Livraria MVC DAO/Livraria.Mvc.AppWeb/Views/Home/Index.cshtml
<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
    <br />
    <h5>Essa aplicação é responsável por gerenciar os livros de sua loja.</h5>
</div>

#01 - Livraria/03 - Livraria MVC DAO/Livraria.Mvc.AppWeb/Views/Livro/Create.cshtml
@model Livraria.Mvc.Domain.Models.Livros.Livro

<h1>Novo Livro</h1>

<hr />

<form asp-action="Create" method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-6">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" placeholder="Digite o nome"/>
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" placeholder="Digite o autor"/>
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edicao" class="control-label"></label>
                <input asp-for="Edicao" class="form-control" placeholder="Digite a edição"/>
                <span asp-validation-for="Edicao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Isbn" class="control-label"></label>
                <input asp-for="Isbn" class="form-control" placeholder="Digite o isbn"/>
                <span asp-validation-for="Isbn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input asp-for="Imagem" class="form-control-file" type="file" accept="image/jpeg" />
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>            
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-dark">Voltar</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

#01 - Livraria/03 - Livraria MVC DAO/Livraria.Mvc.AppWeb/Views/Livro/Delete.cshtml
@model Livraria.Mvc.Domain.Models.Livros.Livro

<h1>Apagar Livro</h1>

<hr />

<form asp-action="Delete" method="post">
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <br />
                <img src="data:image/jpeg;base64, @Model.Imagem" height="385" width="300" alt="Capa do Livro" />
            </div>
        </div>

        <div class="col-md-8">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" readonly />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" readonly />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edicao" class="control-label"></label>
                <input asp-for="Edicao" class="form-control" readonly />
                <span asp-validation-for="Edicao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Isbn" class="control-label"></label>
                <input asp-for="Isbn" class="form-control" readonly />
                <span asp-validation-for="Isbn" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input type="submit" value="Apagar" class="btn btn-danger" />
                <a asp-action="Index" class="btn btn-dark">Voltar</a>
            </div>
        </div>
    </div>
</form>

#01 - Livraria/03 - Livraria MVC DAO/Livraria.Mvc.AppWeb/Views/Livro/Details.cshtml
@model Livraria.Mvc.Domain.Models.Livros.Livro

<h1>Detalhes do Livro</h1>

<hr />

<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <label asp-for="Imagem" class="control-label"></label>
            <br />
            <img src="data:image/jpeg;base64, @Model.Imagem" height="385" width="300" alt="Capa do Livro" />
        </div>
    </div>

    <div class="col-md-8">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Id" class="control-label"></label>
            <input asp-for="Id" class="form-control" readonly/>
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Nome" class="control-label"></label>
            <input asp-for="Nome" class="form-control" readonly/>
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Autor" class="control-label"></label>
            <input asp-for="Autor" class="form-control" readonly/>
            <span asp-validation-for="Autor" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Edicao" class="control-label"></label>
            <input asp-for="Edicao" class="form-control" readonly/>
            <span asp-validation-for="Edicao" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Isbn" class="control-label"></label>
            <input asp-for="Isbn" class="form-control" readonly/>
            <span asp-validation-for="Isbn" class="text-danger"></span>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-dark">Voltar</a>
</div>

#01 - Livraria/03 - Livraria MVC DAO/Livraria.Mvc.AppWeb/Views/Livro/Edit.cshtml
@model Livraria.Mvc.Domain.Models.Livros.Livro

<h1>Editar Livro</h1>

<hr />

<form asp-action="Edit" method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-5">
            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <br />
                <img src="data:image/jpeg;base64, @Model.Imagem" height="460" width="375" alt="Capa do Livro" />
            </div>
        </div>

        <div class="col-md-7">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" placeholder="Digite o nome" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" placeholder="Digite o autor" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edicao" class="control-label"></label>
                <input asp-for="Edicao" class="form-control" placeholder="Digite a edição" />
                <span asp-validation-for="Edicao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Isbn" class="control-label"></label>
                <input asp-for="Isbn" class="form-control" placeholder="Digite o isbn" />
                <span asp-validation-for="Isbn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input asp-for="Imagem" class="form-control-file" type="file" accept="image/jpeg"/>
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-dark">Voltar</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

#01 - Livraria/03 - Livraria MVC DAO/Livraria.Mvc.AppWeb/Views/Livro/Index.cshtml
@model IEnumerable<Livraria.Mvc.Domain.Models.Livros.Livro>

<h1>Livros</h1>

<p><a asp-action="Create">Inserir novo livro</a></p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Imagem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Edicao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Isbn)
            </th>
            <th>
                Ações
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    <img src="data:image/jpeg;base64, @item.Imagem" height="80" width="60" alt="Capa do Livro"/>
                </td>
                <td style="vertical-align: middle;">
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td style="vertical-align: middle;">
                    @Html.DisplayFor(modelItem => item.Autor)
                </td>
                <td style="vertical-align: middle;">
                    @Html.DisplayFor(modelItem => item.Edicao)
                </td>
                <td style="vertical-align: middle;">
                    @Html.DisplayFor(modelItem => item.Isbn)
                </td>
                <td style="vertical-align: middle;">
                    @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Detalhar", "Details", new { id=item.Id }) |
                    @Html.ActionLink("Apagar", "Delete", new { id=item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

#01 - Livraria/03 - Livraria MVC DAO/Livraria.Mvc.AppWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Aplicacao MVC DAO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Aplicacao MVC DAO</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Livro" asp-action="Index">Livros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Aplicacao MVC DAO - Lucas Santos Faria
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>